updated docs for 6.8
elastic/logstash-docs pull request #1244
Opened 2021-12-20 16:59 UTC by logstashmachine

2021-12-20 20:45 UTC, karenzone requested changes
DO NOT MERGE. Contains regressions to docs that will break doc build if merged.  Also contains ECS info not applicable for 6.8.

2021-12-20 20:54 UTC, yaauie commented
ECS info _is_ applicable to these plugins, which _individually_ can be configured to run in ECS mode even on Logstash 6.x.

The difference is that Logstash 6.x (and in fact Logstash < 7.9) provides no way to configure the ECS-compatibility modes for a whole pipeline at once with `pipeline.ecs_compatibility`. Since the setting is absent, each plugin will default to `ecs_compatibility => disabled` but the user can override this on a per-plugin-instance basis.

2021-12-20 20:56 UTC, karenzone commented
Hmmmm... IIRC, that content is "baked in" the `main` docs for all plugins. I'll dig deeper.

2021-12-21 21:15 UTC, karenzone commented on docs/plugins/outputs/elasticsearch.asciidoc
> +- for elasticsearch clusters 6.x and above: the value of 'doc' will be used;
```suggestion
- for elasticsearch clusters 7.x and above: the value of '_doc' will be used;
- for elasticsearch clusters 6.x: the value of 'doc' will be used;
```

2021-12-21 21:36 UTC, karenzone commented
**UPDATE**
I fixed the usual 6.8 suspects (input-file and output-elasticsearch), but pulling in the ECS content to the 6.8 branch has broken additional links because that attribute (apparently) wasn't implemented for the 6.8 branch: 
```
16:23:48 INFO:build_docs:Bad cross-document links:
16:23:48 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/logstash/6.8/plugins-codecs-avro.html contains broken links to:
16:23:48 INFO:build_docs:   - en/ecs/{ecs_version}
16:23:48 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/logstash/6.8/plugins-codecs-csv.html contains broken links to:
16:23:48 INFO:build_docs:   - en/ecs/{ecs_version}
16:23:48 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/logstash/6.8/plugins-inputs-http.html contains broken links to:
16:23:48 INFO:build_docs:   - en/ecs/{ecs_version}
16:23:48 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/logstash/6.8/plugins-inputs-jms.html contains broken links to:
16:23:48 INFO:build_docs:   - en/ecs/{ecs_version}
```

There are several approaches we could use. I'll figure out the best approach, and fix.

2021-12-28 22:02 UTC, karenzone commented
Restesting after merging PR to add attribute to 6.8: 

@elasticmachine run elasticsearch-ci/docs

2021-12-28 22:57 UTC, karenzone approved these changes
Regressions removed and broken cross-doc links resolves. Builds cleanly and renders as expected.

2021-12-28 22:59 UTC, merged